mash-up-kr/hmm_backend_node

README.md, package.json, pnpm-lock.yaml
- package manager pnpm
- readme 수정
- 이거 master에 바로 올려도 괜찮을지 모르겠어서 브랜치따서 올림!
=> fix: 프로젝트 세팅 수정

src/api/friend-list/controller/friend-list.controller.ts, src/api/friend-list/friend-list.module.ts, src/api/friend-list/model/friend-list.entity.ts, src/api/friend-list/service/friend-list.service.ts
=> fix: add friend list entity

src/api/questionnaire/model/questionnaireDetail.entity.ts
=> fix: lint 수정

src/api/questionnaire/model/questionnaire-list.entity.ts
1. QuestionList의 to FK를 Member에서 FriendList로 변경
=> feat: questionnaireList entity to Memeber -> FriendList로 변경

src/api/friend-group/controller/friend-group.controller.ts, src/api/friend-group/model/friend-group.dto.ts
- createGroup API jwt 로 memberId 만들도록 수정
=> fix: createGroup API jwt 로 memberId 만들도록 수정

src/api/friend-group/controller/friend-group.controller.ts, src/api/friend-group/friend-group.module.ts, src/api/friend-group/model/friend-group.response.ts, src/api/friend-group/service/friend-group.service.ts, src/api/friend-list/model/friend-list.entity.ts
=> feat: 그룹조회 API 

src/api/friend-group/controller/friend-group.controller.ts, src/api/friend-group/model/friend-group-save.response.ts, src/api/friend-group/service/friend-group.service.ts
- createGroup API reponse boolean으로 주도록 수정
=> fix: createGroup API reponse boolean으로 주도록 수정

src/api/questionnaire/controller/questionnaire.controller.ts, src/api/questionnaire/model/questionnaire-creation.response.ts, src/api/questionnaire/service/questionnaire.service.ts
=> fix: 질문지 생성 response boolean으로 수정

src/api/questionnaire/controller/questionnaire.controller.ts, src/api/questionnaire/model/questionnaire-answer.response.ts
- fix: 질문지 답변 response boolean으로 수정
-
=> fix: 질문지 답변 response boolean으로 수정

src/api/friend/model/list/friend-list.response.ts, src/api/friend/service/list/friend-list.service.ts
=> fix: return에 friend idx 추가

src/api/member/controller/member.controller.ts, src/api/member/service/member.service.ts, src/main.ts
=> fix: 추천 친구 조회 API return 타입 수정

src/api/alert/alert.module.ts, src/api/alert/model/alert.entity.ts, src/api/friend/controller/friend.controller.ts, src/api/friend/model/friend.response.ts, src/api/friend/service/friend.service.ts
=> fix: 저장된 친구의 friendId 주도록 수정

src/api/friend/controller/friend.controller.ts, src/api/friend/model/friend.dto.ts, src/api/friend/service/friend.service.ts
=> feat: update friend

src/api/friend/controller/friend.controller.ts, src/api/friend/model/friend.dto.ts, src/api/friend/service/friend.service.ts, src/api/questionnaire/controller/questionnaire.controller.ts, src/api/questionnaire/model/profile-read.response.ts, src/api/questionnaire/service/questionnaire.service.ts
- 친구 프로필 상세보기 기능 (친구 정보 + 내 답변 + 친구 답변) 추가
- 컨트롤러가 prefix가 강제로 questionnaire로 붙어있어서 /questionaire/profile/:frienddI로 맵핑되는데 모양새가 안이뻐서,, 더 좋은 방법 있으면 의견 주세요 , ,,
=> feat: 친구 프로필 상세 보기 기능 추가

src/api/member/service/member.service.ts
=> fix: kakao token 만료 시 에러처리

ormconfig.ts, src/api/friend-group/controller/friend-group.controller.ts, src/api/friend-group/service/friend-group.service.ts
=> feat: add delete group API

src/api/friend/controller/friend.controller.ts, src/api/friend/friend.module.ts, src/api/friend/service/friend.service.ts, src/api/friend/service/repository-handler/friend-group-handler.service.ts, src/api/friend/service/repository-handler/friend-list-handler.service.ts
=> fix: refactor friends APIs

src/api/friend-group/controller/friend-group.controller.ts, src/api/friend-group/service/friend-group.service.ts
=> feat: add update group API

src/api/friend-group/friend-group.module.ts, src/api/friend-group/service/friend-group-help-service.ts, src/api/friend-group/service/friend-group.service.ts
=> refactor: group APIs

src/api/friend/controller/friend.controller.ts, src/api/friend/model/friend-query-execute.response.ts, src/api/friend/service/friend.service.ts, src/api/friend/service/repository-handler/friend-list-handler.service.ts
=> feat: delete friend API

src/api/member/controller/member.controller.ts, src/api/member/service/member.service.ts
=> fix: 추천 친구 조회 API URL 변경

src/api/friend/model/friend.entity.ts, src/api/questionnaire/model/questionnaire-list.entity.ts
=> fix: db nullable

src/api/friend/controller/friend.controller.ts, src/api/friend/friend.module.ts, src/api/friend/service/friend.service.ts
=> feat: add find all friends

src/api/questionnaire/model/questionnaire-list.entity.ts, src/api/questionnaire/service/questionnaire.service.ts
- questionnaire list from Member 가져올 수 있게 column 추가
=> fix: questionnaire list from Member 가져올 수 있게 column 추가

src/api/friend-group/model/friend-group.response.ts, src/api/friend-group/service/friend-group-help-service.ts
=> fix: thumbnails urls 빈값말고 null로 채우기

src/api/friend/controller/friend.controller.ts, src/api/friend/model/friend-update.dto.ts, src/api/friend/model/friend.dto.ts, src/api/friend/service/friend.service.ts, src/api/friend/service/repository-handler/friend-list-handler.service.ts
- friend update 기존친구연결에서도 사용하도록 수정
=> fix: friend update 기존친구연결에서도 사용하도록 수정

src/api/friend/service/repository-handler/friend-list-handler.service.ts
=> fix: add isMember field
